version: '3.9'

services:
  database:
    image: postgres
    container_name: db_authentication
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: authentication_jwt_nodejs_databse
    volumes:
      - data_db_authentication:/data/postgres

  api:
    build: .
    container_name: api_authentication
    restart: always
    ports:
      - 3001:3001
      - 9229:9229
    working_dir: /usr/app
    volumes:
      - .:/usr/app

    links:
      - database
    depends_on:
      - database
    command: ['./wait-for-it.sh', 'database:5432', '--', 'npm', 'run', 'dev']

volumes:
  data_db_authentication:
    driver: local
